#!/bin/bash
# USAGE: meddb <keyword1> <keyword2> ... <keywordN>
#        will connect to pubmed via the Lynx web browser (must be installed),
#        run a query for all keywords (AND'ed), 
#        and push the results into the bibliodatabase named "master"
# EXAMPLE: med Wilson 1999

tabname="master" # database table name
dispmax=10   # Max num of refs. Modify this if necessary
string=
for arg ; do string=$string+AND+$arg ; done
string=${string#*+AND+}
lynx -dump "http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Search&db=PubMed&term="$string"&doptcmdl=MEDLINE&dispmax="$dispmax"&title=no" -width=1000 | med2bib >> /tmp/med2bib.$$
bibtodb.pl /tmp/med2bib.$$ $tabname
/bin/rm -f /tmp/med2bib.$$
